name: hack-yeah-backend
services:
- name: web
  github:
    repo: A-N-Ulab/HackYeah2025-back
    branch: master
    deploy_on_push: true
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app