name: hack-yeah-fastapi
services:
- name: web
  github:
    repo: A-N-Ulab/HackYeah2025-back
    branch: master
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py main:app
  health_check:
    http_path: /health