name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy the app to DigitalOcean
        uses: digitalocean/app_action/deploy@v2
#        env:
#          # Any environment variables your app requires can be set here from secrets
#          YOUR_APP_SECRET: ${{ secrets.YOUR_APP_SECRET }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}